export const API_METRICS = {
  Volume: 'Volume',
  Transactions: 'Transactions',
  Addresses: 'Addresses',
  NewAddress: 'NewAddress',
  AddressBalances: 'AddressBalances',
  Supply: 'Supply',
  Nvt: 'Nvt',
  Fees: 'Fees',
  Utxo: 'Utxo',
  Hashrate: 'Hashrate',
  HashrateBtc: 'HashrateBtc',
  Rewards: 'Rewards',
  RewardsBtc: 'RewardsBtc',
  Sopr: 'Sopr',
};
