import {
  BINANCE,
  BITFINEX,
  BITMEX,
  BITSTAMP,
  BITTREX,
  KRAKEN,
  KUCOIN,
  POLONIEX,
  OKEX,
  HUOBI,
  DERIBIT,
  GEMINI,
} from './exchanges';

export const EXCHANGE_IMAGES = {
  [BINANCE]: 'binance.png',
  [BITFINEX]: 'bitfinex.png',
  [BITMEX]: 'bitmex.png',
  [BITSTAMP]: 'bitstamp.png',
  [BITTREX]: 'bittrex.png',
  [KRAKEN]: 'kraken.png',
  [KUCOIN]: 'kucoin.png',
  [POLONIEX]: 'poloniex.png',
  [OKEX]: 'okex.png',
  [HUOBI]: 'huobi.png',
  [DERIBIT]: 'deribit.png',
  [GEMINI]: 'gemini.png',
};

export const MINER_IMAGES = {};

export const TOKEN_IMAGES = {
  USDT: 'usdt.png',
  DAI: 'dai.png',
  GUSD: 'gusd.png',
  PAX: 'pax.png',
  TUSD: 'tusd.png',
  USDC: 'usdc.png',
  BTC: 'btc.png',
  ETH: 'eth.png',
  ANKR: 'ankr.png',
  BAT: 'bat.png',
  BNB: 'bnb.png',
  BNB_ERC20: 'bnb_erc20.png',
  BNT: 'bnt.png',
  BTCB: 'btcb.png',
  BZNT: 'bznt.png',
  CVC: 'cvc.png',
  FET: 'fet.png',
  FTM: 'ftm.png',
  GNT: 'gnt.png',
  KNC: 'knc.png',
  LINK: 'link.png',
  LOOM: 'loom.png',
  MANA: 'mana.png',
  MITH: 'mith.png',
  MKR: 'mkr.png',
  NMR: 'nmr.png',
  OMG: 'omg.png',
  ONE: 'one.png',
  REP: 'rep.png',
  RLC: 'rlc.png',
  SNT: 'snt.png',
  TKN: 'tkn.png',
  USDSB: 'usdsb.png',
  USDT_ERC20: 'usdt (erc20).png',
  USDT_OMNI: 'omni.png',
  ZIL: 'zil.png',
  ZRX: 'zrx.png',
};

export const LOGO_IMAGES = {
  Desktop: 'logo_desktop.png',
  DesktopPro: 'logo_desktop_pro.png',
  Mobile: 'logo_mobile.png',
};
