export const EXCHANGE_IMAGES = {
  Binance: 'binance.png',
  Bitfinex: 'bitfinex.png',
  Bitmex: 'bitmex.png',
  Bitstamp: 'bitstamp.png',
  Bittrex: 'bittrex.png',
  Kraken: 'kraken.png',
  Kucoin: 'kucoin.png',
  Poloniex: 'poloniex.png',
  Okex: 'okex.png',
};

export const COIN_IMAGES = {
  USDT: 'usdt.png',
  DAI: 'dai.png',
  GUSD: 'gusd.png',
  PAX: 'pax.png',
  TUSD: 'tusd.png',
  USDC: 'usdc.png',
  BTC: 'btc.png',
  ETH: 'eth.png',
  ANKR: 'ankr.png',
  BAT: 'bat.png',
  BNB: 'bnb.png',
  BNB_ERC20: 'bnb_erc20.png',
  BNT: 'bnt.png',
  BTCB: 'btcb.png',
  BZNT: 'bznt.png',
  CVC: 'cvc.png',
  FET: 'fet.png',
  FTM: 'ftm.png',
  GNT: 'gnt.png',
  KNC: 'knc.png',
  LINK: 'link.png',
  LOOM: 'loom.png',
  MANA: 'mana.png',
  MITH: 'mith.png',
  MKR: 'mkr.png',
  NMR: 'nmr.png',
  OMG: 'omg.png',
  ONE: 'one.png',
  REP: 'rep.png',
  RLC: 'rlc.png',
  SNT: 'snt.png',
  TKN: 'tkn.png',
  USDSB: 'usdsb.png',
  USDT_ERC20: 'usdt (erc20).png',
  ZIL: 'zil.png',
  ZRX: 'zrx.png',
};

export const LOGO_IMAGES = {
  Desktop: 'logo_desktop.png',
  DesktopPro: 'logo_desktop_pro.png',
  Mobile: 'logo_mobile.png',
};
