export const TOKEN_NAMES = {
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  USDT: 'Tether',
  DAI: 'DAI',
  OMG: 'OmiseGO',
  PAX: 'Paxos',
  TUSD: 'TrueUSD',
  USDC: 'USD Coin',
  GUSD: 'Gemini Dollar',
  LINK: 'Chainlink',
  ZIL: 'Zilliqa',
  BAT: 'Basic Attention Token',
  BNT: 'Bancor',
  CVC: 'Civic',
  FET: 'Fetch',
  GNT: 'Golem',
  KNC: 'Kyber Network',
  LOOM: 'Loom',
  MANA: 'Decentraland',
  MKR: 'Maker',
  NMR: 'Numeraire',
  REP: 'Augur',
  RLC: 'RLC',
  SNT: 'Status',
  TKN: 'Monolith',
  USDT_ERC20: 'Tether',
  USDT_OMNI: 'Tether (OMNI)',
  ZRX: '0x',
};
