export const STABLE_TOKENS = {
  // ANKR: 'ANKR',
  BAT: 'BAT',
  // BNB: 'BNB',
  // BNB_ERC20: 'BNB_ERC20',
  BNT: 'BNT',
  // BTCB: 'BTCB',
  // BZNT: 'BZNT',
  CVC: 'CVC',
  DAI: 'DAI',
  FET: 'FET',
  // FTM: 'FTM',
  GNT: 'GNT',
  GUSD: 'GUSD',
  KNC: 'KNC',
  LINK: 'LINK',
  LOOM: 'LOOM',
  MANA: 'MANA',
  // MITH: 'MITH',
  MKR: 'MKR',
  NMR: 'NMR',
  OMG: 'OMG',
  // ONE: 'ONE',
  PAX: 'PAX',
  REP: 'REP',
  RLC: 'RLC',
  SNT: 'SNT',
  TKN: 'TKN',
  TUSD: 'TUSD',
  USDC: 'USDC',
  // USDSB: 'USDSB',
  USDT: 'USDT',
  USDT_ERC20: 'USDT_ERC20',
  USDT_OMNI: 'USDT_OMNI',
  ZIL: 'ZIL',
  ZRX: 'ZRX',
};

export const NATIVE_TOKENS = {
  BTC: 'BTC',
  ETH: 'ETH',
};

export const CURRENCIES = {
  USD: 'USD',
  EUR: 'EUR',
};
