export const STABLE_TOKENS = {
  USDT: "USDT",
  USDT_OMNI: "USDT_OMNI",
  USDT_ERC20: "USDT_ERC20",
  USDC: "USDC",
  PAX: "PAX",
  DAI: "DAI",
  TUSD: "TUSD",
  GUSD: "GUSD",
  OMG: "OMG",
  LINK: "LINK",
  MANA: "MANA",
  GNT: "GNT",
  FET: "FET",
  LOOM: "LOOM",
  ZIL: "ZIL",
  BAT: "BAT",
  REP: "REP",
  CVC: "CVC",
  ZRX: "ZRX",
  RLC: "RLC",
  TKN: "TKN",
  SNT: "SNT",
  GNT: "GNT",
  KNC: "KNC",
  MKR: "MKR",
  BNT: "BNT",
  BNB: "BNB",
  BNB_ERC20: "BNB_ERC20",
  NMR: "NMR",
  USDSB: "USDSB",
  BZNT: "BZNT",
  ONE: "ONE",
  BTCB: "BTCB",
  ANKR: "ANKR",
  MITH: "MITH",
  FTM: "FTM"
};

export const NATIVE_TOKENS = {
  BTC: "BTC",
  ETH: "ETH"
};
