export const BTC_STUDIES = [
  {
    symbol: '#TRANSACTIONS',
    urlSlug: 'token_count_window_historical',
    dataPoint: 'number_of_txns',
  },
  {
    symbol: '#VOLUMEUSD',
    urlSlug: 'token_volume_window_historical',
    dataPoint: 'volume_real_usd',
  },
  {
    symbol: '#VOLUMEREAL',
    urlSlug: 'token_volume_window_historical',
    dataPoint: 'volume_real',
  },
  {
    symbol: '#VOLUMECHANGEUSD',
    urlSlug: 'token_volume_window_historical',
    dataPoint: 'volume_change_usd',
  },
  {
    symbol: '#VOLUMECHANGEREAL',
    urlSlug: 'token_volume_window_historical',
    dataPoint: 'volume_change',
  },
  {
    symbol: '#ACTIVESENDERS',
    urlSlug: 'token_active_address_window_historical',
    dataPoint: 'active_senders',
  },
  {
    symbol: '#ACTIVERECIPIENTS',
    urlSlug: 'token_active_address_window_historical',
    dataPoint: 'active_recipients',
  },
  {
    symbol: '#SUPPLY',
    urlSlug: 'token_supply_window_historical',
    dataPoint: 'supply',
  },
  {
    symbol: '#NVT',
    urlSlug: 'token_supply_window_historical',
    dataPoint: 'supply',
  },
  {
    symbol: '#MARKETCAP',
    urlSlug: 'token_supply_window_historical',
    dataPoint: 'supply',
  },
  {
    symbol: '#TOTALFEESREAL',
    urlSlug: 'token_fees_window_historical',
    dataPoint: 'total_fee',
  },
  {
    symbol: '#TOTALFEESUSD',
    urlSlug: 'token_fees_window_historical',
    dataPoint: 'total_fee_usd',
  },
  {
    symbol: '#AVERAGEFEESREAL',
    urlSlug: 'token_fees_window_historical',
    dataPoint: 'avg_fee',
  },
  {
    symbol: '#AVERAGEFEESUSD',
    urlSlug: 'token_fees_window_historical',
    dataPoint: 'avg_fee_usd',
  },
  {
    symbol: '#AVERAGESIZEBYTES',
    urlSlug: 'token_fees_window_historical',
    dataPoint: 'avg_size_bytes',
  },
  {
    symbol: '#AVERAGESATOSHIS',
    urlSlug: 'token_fees_window_historical',
    dataPoint: 'avg_satoshis_per_byte',
  },
  {
    symbol: '#<1D',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '<1d',
  },
  {
    symbol: '#1-3M',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '1-3m',
  },
  {
    symbol: '#3-6M',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '3-6m',
  },
  {
    symbol: '#6-12M',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '6-12m',
  },
  {
    symbol: '#12-18M',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '12-18m',
  },
  {
    symbol: '#18-24M',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '18-24m',
  },
  {
    symbol: '#1D-1W',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '1d-1w',
  },
  {
    symbol: '#1W-1M',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '1w-1m',
  },
  {
    symbol: '#2Y-3Y',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '2-3y',
  },
  {
    symbol: '#3Y-5Y',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '3-5y',
  },
  {
    symbol: '#5Y-10Y',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '5-10y',
  },
  {
    symbol: '#>10Y',
    urlSlug: 'token_utxo_age_window_historical',
    dataPoint: '>10y',
  },
];

export const BTC_SYMBOLS = [
  { symbol: '#TRANSACTIONS' },
  { symbol: '#VOLUMEUSD' },
  { symbol: '#VOLUMEREAL' },
  { symbol: '#VOLUMECHANGEUSD' },
  { symbol: '#VOLUMECHANGEREAL' },
  { symbol: '#ACTIVESENDERS' },
  { symbol: '#ACTIVERECIPIENTS' },
  { symbol: '#SUPPLY' },
  { symbol: '#NVT' },
  { symbol: '#MARKETCAP' },
  { symbol: '#TOTALFEESREAL' },
  { symbol: '#TOTALFEESUSD' },
  { symbol: '#AVERAGEFEESREAL' },
  { symbol: '#AVERAGEFEESUSD' },
  { symbol: '#AVERAGESIZEBYTES' },
  { symbol: '#AVERAGESATOSHIS' },
  { symbol: '#<1D' },
  { symbol: '#1-3M' },
  { symbol: '#3-6M' },
  { symbol: '#6-12M' },
  { symbol: '#12-18M' },
  { symbol: '#18-24M' },
  { symbol: '#1D-1W' },
  { symbol: '#1W-1M' },
  { symbol: '#2Y-3Y' },
  { symbol: '#3Y-5Y' },
  { symbol: '#5Y-10Y' },
  { symbol: '#>10Y' },
];
